### ISSUE TITLE
API报错，主人回来看看吧

### ISSUE THREAD

**Issue by TrueRux** [ruter/xiachufang-api#4]
返回  'list' object has no attribute 'strip'
请问是什么问题？

**Comment by ruter** [comment]
请问是什么情况下报错的？麻烦贴上详细的错误信息，这样才可以定位。

`strip()` 方法是字符串的方法，这里目前猜测是获取到的数据是一个列表，而非预期的字符串。

**Comment by TrueRux** [comment]
情况1：url为：http://192.168.2.129:5000/search/鸡蛋
情况2：url为：http://192.168.2.129:5000/category/394/
我也觉得应该返回的数组引发了这个错误。不过我第一次接触python，昨晚尝试着去调试python代码，但是没有成功。所以就想过来问问。麻烦了哈

**Comment by ruter** [comment]
已修复 #5 
这个问题是因为下厨房的菜谱列表 DOM 结构发生变化导致的

**Comment by TrueRux** [comment]
谢谢

**Comment by TrueRux** [comment]
请问服务器可以配置https然后这个api吗？

**Comment by ruter** [comment]
@TrueRux 可以

**Comment by TrueRux** [comment]
请问是怎样更换端口的？例如我现在的5000端口被占用了，想要换成其它的端口。我尝试了一下在改变缓存方式那里更改端口，但是没有成功。
