### ISSUE TITLE
请问是怎样更换端口的？例如我现在的5000端口被占用了，想要换成其它的端口。我尝试了一下在改变缓存方式那里更改端口，但是没有成功。

### ISSUE THREAD

**Issue by ruter** [ruter/xiachufang-api#6]
_Originally posted by @TrueRux in https://github.com/ruter/xiachufang-api/issues/4#issuecomment-429506498_

**Comment by ruter** [comment]
在 `config/gunicorn.py` 里，找到 `bind = '0.0.0.0:5000'`

`5000` 改成你想要的端口

@TrueRux

**Comment by TrueRux** [comment]
非常感谢 @ruter
