### ISSUE TITLE
获取菜单报错

### ISSUE THREAD

**Issue by TrueRux** [ruter/xiachufang-api#7]
出错Url：http://www.xiachufang.com/category/40076/
错误信息：[Parsed  ] FAIL Item<Recipe[0]>
备注：个人觉得是 category.py的问题，原因也是应该页面DOM页面修改了。但是改了两个小时都没有效果。想知道问题所在，谢谢大神回复。

**Comment by ruter** [comment]
> 出错Url：http://www.xiachufang.com/category/40076/
> 错误信息：[Parsed ] FAIL Item<Recipe[0]>
> 备注：个人觉得是 category.py的问题，原因也是应该页面DOM页面修改了。但是改了两个小时都没有效果。想知道问题所在，谢谢大神回复。

发生变更的结构是菜谱列表的外层，需要修改 `items/recipe.py`:

```python
class Meta:
    source = XPath('//div[contains(@class, "main-panel")]//div[@class="normal-recipe-list"]/ul[@class="list"]/li')
```
